### ISSUE TITLE
Exception Investigation:  werkzeug.exceptions:MethodNotAllowed

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1392]
This is one of the errors we've seen captured in New Relic that we'd like to dig into and understand, if not also resolve.

**Error message:**
405 Method Not Allowed: The method is not allowed for the requested URL.
Path:  /
Exception:  werkzeug.exceptions:MethodNotAllowed

```
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/eventlet/greenthread.py", line 221, in main
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/geventlet.py", line 157, in handle
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 55, in handle
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/newrelic/api/wsgi_application.py", line 669, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 2213, in __call__
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/notifications_utils/request_helper.py", line 80, in __call__
File "/home/vcap/app/app/proxy_fix.py", line 11, in __call__
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/werkzeug/middleware/proxy_fix.py", line 182, in __call__
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/newrelic/api/wsgi_application.py", line 564, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1458, in dispatch_request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/app.py", line 1440, in raise_routing_exception
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/flask/ctx.py", line 353, in match_request
File "/home/vcap/deps/0/python/lib/python3.9/site-packages/werkzeug/routing/map.py", line 619, in match
```

## Implementation Sketch and Acceptance Criteria

- [ ] Look through our log history at https://logs.fr.cloud.gov/ and see if any patterns emerge that might indicate what conditions cause this
- [ ] Try and replicate the error, if possible
- [ ] Follow up in this issue with any findings and possible remediation steps

## Security Considerations

- Be mindful of not sharing sensitive information.
- We'd like to reduce the errors that occur in the application where possible to maintain application stability and performance, and reduce the chances that the application ends up in an error or invalid state.

**Comment by terrazoon** [comment]
"POST / HTTP/1.1" 405

**Comment by terrazoon** [comment]
This looks like some script is going to our sign-in page, finding all the relative paths, and then just posting to them to see what happens.  It seems like we are already remediating by returning a 405.

**Comment by ccostino** [comment]
That sure seems to be the case, thanks for taking a closer look, @terrazoon!

The only thing I find odd about this is that a full stack trace is being thrown instead of just returning a 405 response.  Is there something we can do or should change with the [`request_helper.py`](https://github.com/GSA/notifications-admin/blob/main/notifications_utils/request_helper.py#L80) file?

If so, it doesn't have to be with this issue, we should write up a new one for any adjustments, because in looking at it quick there is likely more than just a one-line fix.  Ultimately, we should be able to return the 405 response without a whole stack trace being thrown.
