### ISSUE TITLE
QA for prod push on 5/30/2024

### ISSUE THREAD

**Issue by ccostino** [GSA/notifications-admin#1572]
### Log In

- [x] notify-staging.app.cloud.gov resolves
- [x] Clicking sign in takes you to login page
- [x] 2FA code is sent promptly
- [x] 2FA code input screen appears as expected
- [x] After code is entered, you are brought to the “choose service” screen
- [x] Choosing a service brings you to the dashboard for that service

### Create a template and send

- [x] Clicking “Send messages” brings you to templates page
- [x] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [x] Uploading a csv is quick and automatically directs you to the preview/send page
- [x] Formatting looks clean and in place
- [x] Message dashboard populates and shows “pending” until call is made to AWS for delivery receipt

### Send a message from copied template

- [x] When “Create a template” button is clicked, the option to create new or copy existing template appears
- [x] Clicking “copy an existing template” allows you to choose from pre-existing template
- [x] After editing, the new template saves and you prepare to send

### Send a message from existing template

- [x] Clicking on existing template brings you to preview screen with `prepare to send` button
- [x] All else above persists as true (formatting, send, dashboard, etc)

### Download the csv delivery report

- [x] Clicking on the csv download directly after a message send downloads a report that contains the data we expect
- [x] The batch report appears on the main dashboard batch table with accurate information
- [x] Clicking on the csv download link from the main dashboard downloads a report that contains the data we expect

### Invite a team member

- [x] Clicking on “Team” in settings  brings you to team member screen
- [x] Clicking “Invite a team member” brings you to email and permissions screen
- [x] Clicking invite team member sends an invite and shows confirmation
- [x] Invite email provides live link that works to register new team member

### Delete a team member

- [x] From team member screen, clicking “Change Details” on a specific profile brings you to that person’s profile
- [x] Clicking on “Remove this team member” prompts a confirmation
- [x] Clicking the confirmation removes the team member

### Sign Out

- [x] Hitting “Sign Out” takes you back to the homepage and logs you out

**Comment by ccostino** [comment]
Noting an issue that we've found in staging:  one-off message sends take extra time to get sent out.

In all environments, triggering a one-off send results in an error being thrown:

**No row was found when one was required**

```
Traceback (most recent call last):
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/eventlet/greenthread.py", line 265, in main
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/geventlet.py", line 157, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 55, in handle
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/gunicorn/workers/base_async.py", line 108, in handle_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 669, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
File "/home/vcap/app/notifications_utils/request_helper.py", line 80, in __call__
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/api/wsgi_application.py", line 564, in _nr_wsgi_application_wrapper_
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/newrelic/hooks/framework_flask.py", line 79, in _nr_wrapper_handler_
File "/home/vcap/app/app/job/rest.py", line 46, in get_job_by_service_and_job_id
File "/home/vcap/app/app/dao/jobs_dao.py", line 45, in dao_get_job_by_service_id_and_job_id
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2778, in one
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1810, in one
File "/home/vcap/deps/0/python/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 752, in _only_one_row
```

[This is being thrown in `jobs_dao.py`](https://github.com/GSA/notifications-api/blob/main/app/dao/jobs_dao.py#L44-L45), but appears to also be handled; the messages still get sent just fine.

The error is already happening in production as it is, and no other issues were found during QA.

**Comment by ccostino** [comment]
[A bug issue](https://github.com/GSA/notifications-api/issues/1033) has been filed for the error.

**Comment by ccostino** [comment]
Prod deploy is done as of 5/30/2024!
